import Crypto from './crypto';
const crypto = require('crypto');

// The validator should sit on the smart device.
// The signer needs to create trust for the backend. This is done via a blinded
// secret generated by the smart device. The device will be registered via the
// public key onto the blockchain.
export default class Device {
  // the amount should be inferred somehow from the events on device
  constructor(clientPk, amount) {
    // generate private and public keys
    const { privateKey, publicKey } = crypto.generateKeyPairSync('ec', {
      namedCurve: 'sect239k1',
      publicKeyEncoding:  { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' }
    });

    this.privateKey = privateKey;
    this.publicKey = publicKey;

    this.clientPk = clientPk;
    this.amount   = amount;
  }

  // the message that arrives to the validator should be signed
  sign() {
    // to sign the message, together with the nonce
    const message = this.clientPk + '|' + this.amount;

    // get the signature
    const signature = new Crypto().sign(
      new Crypto().hash(message),
      this.privateKey
    );
    return signature;
  }

  exportDeviceKey() {
    return this.publicKey;
  }

  exportClientKey() {
    return this.clientPk;
  }

  exportAmount() {
    return this.amount;
  }
}
